<?php
// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>
<div class="pdp-gallery" data-gallery-role="gallery-placeholder"></div>
<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "productGallery": {
                "galleryImagesJson": <?= /* @escapeNotVerified */ $block->getGalleryImagesJson() ?>,
                "videoAutoPlay": true,
                "isMobileMediaQuery": "(max-width: 768px)",
                "videoUrlParameters": {
                    "autoplay": 1
                },
                "mainCarousel": ".js-gallery-main",
                "thumbnailCarousel": ".js-gallery-thumbnails",
                "options": {
                    "slidesToShow": 1,
                    "slidesToScroll": 1,
                    "arrows": false,
                    "infinite": false
                },
                "thumbnailOptions": {
                    "responsive": [
                        {
                            "breakpoint": 768,
                            "settings": {
                                "focusOnSelect": true,
                                "infinite": false,
                                "slidesToShow": 3,
                                "slidesToScroll": 1,
                                "swipeToSlide": true,
                                "arrows": false
                            }
                        }, {
                            "breakpoint": 4000,
                            "settings": {
                                "focusOnSelect": true,
                                "infinite": false,
                                "prevArrow": "<button type=\"button\" class=\"slick-prev\"><\/button>",
                                "nextArrow": "<button type=\"button\" class=\"slick-next\"><\/button>",
                                "slidesToShow": 6,
                                "slidesToScroll": 1,
                                "swipeToSlide": true
                            }
                        }
                    ]
                },
                "fancyboxOptions": {
                    "buttons": [
                        "zoom",
                        "thumbs",
                        "close"
                    ]
                }
            }
        }
    }
</script>
